name: ndvi
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - bokeh=2.3.3=py39haa95532_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.9.30=haa95532_1
  - cached-property=1.5.2=py_0
  - cartopy=0.18.0=py39h80a4efb_1
  - certifi=2021.10.8=py39haa95532_0
  - cffi=1.14.6=py39h2bbff1b_0
  - cfitsio=3.470=he774522_6
  - cftime=1.5.0=py39h080aedc_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py39haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - colorcet=2.0.6=pyhd3eb1b0_0
  - cryptography=3.4.8=py39h71e12ea_0
  - curl=7.78.0=h86230a5_0
  - cycler=0.10.0=py39haa95532_0
  - cytoolz=0.11.0=py39h2bbff1b_0
  - dask=2021.8.1=pyhd3eb1b0_0
  - dask-core=2021.8.1=pyhd3eb1b0_0
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py39haa95532_1
  - debugpy=1.4.1=py39hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.8.1=py39haa95532_0
  - entrypoints=0.3=py39haa95532_0
  - expat=2.4.1=h6c2663c_2
  - fiona=1.8.13.post1=py39h758c064_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=h2bbff1b_0
  - fsspec=2021.8.1=pyhd3eb1b0_0
  - gdal=3.0.2=py39hb978731_1
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.6.0=h5770a2b_0
  - geoviews=1.9.1=pyhd3eb1b0_0
  - geoviews-core=1.9.1=pyh06a4308_0
  - h5py=3.2.1=py39h3de5c98_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h7ebc959_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.6=pyhd3eb1b0_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.4.1=py39haa95532_1
  - ipython=7.27.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.4=pyhd3eb1b0_0
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39haa95532_7
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kealib=1.4.14=hde4a422_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - libcurl=7.78.0=h86230a5_0
  - libgdal=3.0.2=ha1b3edf_1
  - libiconv=1.15=h1df5818_7
  - libnetcdf=4.6.1=hf59b723_4
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.2=hb652d5d_1
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.2.0=hd0e1b90_0
  - libxml2=2.9.12=h0ad7f3c_0
  - llvmlite=0.36.0=py39h34b8924_4
  - locket=0.2.1=py39haa95532_1
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markdown=3.3.4=py39haa95532_0
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib-base=3.4.2=py39h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msgpack-python=1.0.2=py39h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py39haa95532_0
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - netcdf4=1.5.7=py39hb76ebac_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - notebook=6.4.3=py39haa95532_0
  - numba=0.53.1=py39hf11a4ad_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.21.2=py39hfca59bb_0
  - numpy-base=1.21.2=py39h0829f74_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1l=h2bbff1b_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.3=py39h6214cd6_0
  - pandocfilters=1.4.3=py39haa95532_1
  - panel=0.12.1=pyhd3eb1b0_0
  - param=1.11.1=pyhd3eb1b0_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py39haa95532_0
  - postgresql=12.2=hb652d5d_1
  - proj=6.2.1=h9f7ef89_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.8.0=py39h2bbff1b_1
  - pycparser=2.20=py_2
  - pyct=0.4.6=py39haa95532_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py39h593ac45_1
  - pyqt=5.9.2=py39hd77b12b_6
  - pyreadline=2.1=py39haa95532_1
  - pyrsistent=0.18.0=py39h2bbff1b_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywin32=228=py39hbaba5e8_1
  - pywinpty=0.5.7=py39haa95532_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - pyzmq=22.2.1=py39hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - requests=2.26.0=pyhd3eb1b0_0
  - rtree=0.9.7=py39h2eaa2aa_1
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scipy=1.7.1=py39hbe87c03_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39haa95532_0
  - shapely=1.7.1=py39h06580b3_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2020.3=h74a9793_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.2.9=hf7ce2e6_0
  - tk=8.6.11=h2bbff1b_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - winpty=0.4.3=4
  - xarray=0.19.0=pyhd3eb1b0_1
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - cachetools==4.2.4
    - click==8.0.3
    - earthengine-api==0.1.290
    - future==0.18.2
    - google-api-core==1.31.4
    - google-api-python-client==1.12.8
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.2.1
    - google-cloud-storage==1.42.3
    - google-crc32c==1.3.0
    - google-resumable-media==2.1.0
    - googleapis-common-protos==1.53.0
    - httplib2==0.20.2
    - httplib2shim==0.0.3
    - planet==1.4.7
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-futures==0.9.7
    - rsa==4.7.2
    - uritemplate==3.0.1
prefix: C:\Users\bella\Anaconda3\envs\ndvi

